service: sls-lamda-helloworld
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

package:
    exclude:
      - .vscode/**

functions:
  time:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: post
